blueprint:
  name: Litter Robot Auto Reset
  description: Auto power-cycle a Litter Robot that has gotten stuck
  domain: automation
  input:
    power_switch:
      name: Smart Plug
      description: Smart plug that the litter robot is plugged into
      selector:
        device:
          entity:
            domain: switch
    litter_box:
      name: Litter Robot
      description: The Litter Robot device to automate
      selector:
        device:
          integration: Litter-Robot
          entity:
            domain: vacuum
          multiple: false
  trigger:
    - platform: state
      entity_id:
        !input litter_box
      attribute: status
      to: BR
  actions:
    - delay:
        hours: 0
        minutes: 5
        seconds: 0
        milliseconds: 0
    - condition: state
      entity_id: !input litter_box
      state: error
    - service: switch.turn_off
      data: {}
      target: !input power_switch
    - delay:
        hours: 0
        minutes: 0
        seconds: 30
        milliseconds: 0
    - service: switch.turn_on
      data: {}
      target: !input power_switch
  mode: single
